### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by esutton32** [esutton32/digitalmedia#1]
# To-do

- [ ] Write up bio
- [ ] Do fun facts section
- [ ] Fix placeholders
- [ ] Put in new images
- [ ] Generally make the site look nicer
